import { Report, ReportStatus } from "../../types/Report";

const reportInitialValues: Report = {
  _id: 0,
  reviewersEmail: [],
  segment: "",
  office: "",
  machineNumber: "",
  timestampCraftsmanship: "",
  hoursDelay: "",
  techBucket: "",
  machineFamily: "",
  description: "",
  mealTime: false,
  continuousWork: false,
  experienced: false,
  gotTraining: false,
  customerInterference: false,
  workAlone: false,
  background: "",
  myselInfluence: "",
  riskReduceDescription: "",
  teamInfluence: "",
  managerInfluence: "",
  status: ReportStatus.NEW,
  archived: false,
  permissions: {
    CanSubmit: false,
    CanUnsubmit: false,
    CanReview: false,
    CanEdit: false,
    CanClose: false,
    CanDelete: false,
    CanEditClose: false,
    CanAlwaysDelete: false,
  },
  answers: [],
  reportNumber: "",
  submitterEmail: "",
  filePath: null,
  filePathSecond: null,
  filePathThird: null,
  downloadFileURL: null,
  downloadFileUrlSecond: null,
  downloadFileUrlThird: null,
};

export default reportInitialValues;
